### ISSUE TITLE
QUESTION: Post requests to update content

### ISSUE THREAD

**Issue by KartikChugh** [Frozen-Flask/Frozen-Flask#105]
My understanding of static webpages, Flask, and Frozen-Flask is limited. Is it possible to use Frozen-Flask on this [project](https://github.com/KartikChugh/Spam-Classifier/blob/flask-freeze/server.py), where a form on index.html sends a POST request to the /predict page to render some content?

**Comment by tswast** [comment]
Any sort of rendering you do based on POST variables would have to be done server-side, which is not a good fit for Frozen-Flask. If there's a limited set of possible renderings, you could pass in the needed values as URL parameters to have Frozen-Flask render them.

For your project, it looks like you're doing some ML classification. Something like https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/ to run Python in the browser may work for you. You'll still need to pass the variables in a different way, as the browser does not have access to POST data. In that situation, I've saved data to `sessionStorage` at form submission time.
