### ISSUE TITLE
Test fail on python3.x

### ISSUE THREAD

**Issue by AlvaroMaceda** [Frozen-Flask/Frozen-Flask#106]
I've run the tests out-of-the-box and there is a test failing with 3x python versions:

```
ERROR: test_importing_collections (__main__.TestPythonCompatibilityWarnings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alvaro/Software/Frozen-Flask/.tox/py35/lib/python3.5/site-packages/flask_frozen/tests.py", line 532, in test_importing_collections
    stderr=subprocess.STDOUT)
  File "/home/alvaro/.pyenv/versions/3.5.9/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/home/alvaro/.pyenv/versions/3.5.9/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/alvaro/Software/Frozen-Flask/.tox/py35/bin/python', 'flask_frozen/__init__.py']' returned non-zero exit status 2
```

The test fails at this instruction:
`subprocess.check_output([sys.executable, 'flask_frozen/__init__.py'],stderr=subprocess.STDOUT)`

The problem seems to be that it is in 'docs' directory before executing  subprocess.check_output, therefore it doesn't find flask_frozen directory (it should be ../flask_frozen)

I've seen that tox.ini changes directory to docs. If I change tox.ini, everything runs fine:
```
[testenv]
commands=python -m flask_frozen.tests
changedir=.
```

I'm not sure if it's a local development problem or it's a problem with Flask. I'd appreciate some help.

**Comment by honzajavorek** [comment]
Hi @AlvaroMaceda, I see you're using Python 3.5, which should be supported and is tested, but just by chance, would you mind trying this with a newer Python version?
