### ISSUE TITLE
Update to Flask 2.0 and drop Python 2.7

### ISSUE THREAD

**Issue by tswast** [Frozen-Flask/Frozen-Flask#112]
Flask 2.0 was recently released. https://palletsprojects.com/blog/flask-2-0-released/

This release drops support for Python 2.7 and Python 3.5, which should simplify our tests.

**Comment by honzajavorek** [comment]
I'm far from being able to be very active around here, which I'm sorry about. However, chiming in with a very fresh experience. Yesterday evening I've spent a few hours hopelessly debugging a project running on Frozen-Flask. Some static files were not propagated properly and I couldn't figure out why. Then I recalled earlier I upgraded Flask to v2. Downgrading solved the problem.

I don't have further details (yet), but whoever runs Frozen-Flask with Flask v2, be warned it might **silently** skip some pretty much randomly selected static files, in my case images. It won't crash, all will look good, but they'll be missing in the output directory. I observed this with both images linked from CSS and from HTML.

Perhaps it's something very specific about my project, but when upgrading to Flask v2, we should verify this or at least watch out for a better bug report.
