### ISSUE TITLE
Some static files are not served with Flask 2.0

### ISSUE THREAD

**Issue by encukou** [Frozen-Flask/Frozen-Flask#113]
Flask 2.0 seems to have made changes around serving static files, and [Frozen-Flask's approach](https://github.com/Frozen-Flask/Frozen-Flask/blob/3e0d53479779dcffa96173cf5eb36dfe406d980a/flask_frozen/__init__.py#L426) no longer finds all static files.

See also: https://github.com/Frozen-Flask/Frozen-Flask/issues/112#issuecomment-841629172, https://github.com/Frozen-Flask/Frozen-Flask/pull/111#issuecomment-845868949

**Comment by jayaddison** [comment]
Working on a little more confirmation here, but it looks like this may relate to https://github.com/pallets/flask/pull/3762 (included in Flask 2.x).

We use a test at https://github.com/Frozen-Flask/Frozen-Flask/blob/435bd1cd5369a743a22a6cb0210a0fa974cdd5ac/flask_frozen/__init__.py#L439-L440 to check whether each view function is the same as the `send_static_file` method, and yield the matching endpoint names.

With the introduction of the lambda function 'in front' of the `send_static_file` method, the equality check will not pass, the static endpoint is skipped from the list of `Frozen-Flask` static rules, and the contents aren't retrieved for freezing into the resulting document set.

**Comment by jayaddison** [comment]
Because it didn't seem clear how `Flask-Frozen` could fix this easily, I thought it might be worth asking the `flask` community whether they have any ideas or suggestions.

This has been opened as a GitHub discussion (filed as Q&A) here: https://github.com/pallets/flask/discussions/4136

**Comment by honzajavorek** [comment]
Hi @jayaddison, this is amazing work, thank you so much! I haven't had much time lately to assist here, I'm sorry for that.

**Comment by jayaddison** [comment]
No problem at all @honzajavorek; thanks for maintaining the library.  I'd offer some time if I could, but not sure I can promise much; I'll try to check in on the health of `frozen-flask` when possible.

**Comment by honzajavorek** [comment]
I'd be happy to see you around! Thank you for the work on this issue, I think that was already an excellent way how you helped this project :)
