### ISSUE TITLE
Not clear how to write URL generators based on documentation

### ISSUE THREAD

**Issue by Zenahr** [Frozen-Flask/Frozen-Flask#116]
I've read the documentation found at https://pythonhosted.org/Frozen-Flask/#url-generators and to be fair I'm just confused by it.

I've tried a multitude of approaches, but nothing worked.

Here's my current code:

```py
@app.route('/category/<category_slug>')
def articles(category_slug):
    data = []
    for article in ARTICLES:
        if article.metadata['category'] == category_slug:
            data.append(article)
    return render_template('category.html', articles=data)


@freezer.register_generator
def articles_generator():
    for article in ARTICLES:
        yield {'/articles/' + article.metadata['slug'], article}


@app.route('/articles/<slug>')
def article(slug):
    for article in ARTICLES:
        if article.metadata['slug'] == slug:
            return render_template('article.html', article=article, thumb=article.metadata['thumb'])
    return page_not_found(404)

@freezer.register_generator
def article_generator():
    yield {'article', article.metadata['slug']}
```

the error I get is as follows:

```
MissingURLGeneratorWarning: Nothing frozen for endpoints articles, article. Did you forget a URL generator?
  return set(page.url for page in self.freeze_yield())
```

Any clarifications would be greatly appreciated.

**Comment by Zenahr** [comment]
here's another approach I've tried for `articles`:

```py
@freezer.register_generator
def articles_generator():
    data = []
    for article in ARTICLES:
        if article.metadata['category'] == category_slug:
            data.append(article)
    yield {'/articles/' + data['slug'], data}
```

**Comment by encukou** [comment]
You need to give Frozen-Flask the *endpoint name* and *arguments*, like you would use for Flask's `url_for` function:
```python
@freezer.register_generator
def article_generator():
    for article in ARTICLES:
        yield 'article', {'slug': article.metadata['slug']}
```
or you can generate URLs directly and yield those:
```python
@freezer.register_generator
def article_generator():
    for article in ARTICLES:
        yield url_for('article', slug=article.metadata['slug'])
```
or you can leave the endpoint name out, and Frozen-Flask will use the name of the function:
```python
@freezer.register_generator
def article():  # function name matters here!
    for article in ARTICLES:
        yield {'slug': article.metadata['slug']}
```
(None of these are tested; hopefully they show the right way.)

**Comment by Zenahr** [comment]
Hi @encukou 
thanks for the quick reply!

I've taken one of your example snippets but still get this error: ```MissingURLGeneratorWarning: Nothing frozen for endpoints article. Did you forget a URL generator?```

How come I get this error message even though I've defined this function?:

```
@app.route('/articles/<slug>')
def article(slug):
    for article in ARTICLES:
        if article.metadata['slug'] == slug:
            return render_template('article.html', article=article, thumb=article.metadata['thumb'])
    return page_not_found(404)

@freezer.register_generator
def article_generator():
    for article in ARTICLES:
        yield 'article', {'slug': article.metadata['slug']}
```

My `view function` for this route is `article` and the argument it takes in is `slug`. This seems fine to me but of course it's still not working.

I've completely removed the `articles` endpoint just in case it's colluding with the `article` endpoint URL generator.

**Comment by encukou** [comment]
And do you have any ARTICLES?

This complete example works for me:
```python
from flask import Flask
from flask_frozen import Freezer

app = Flask(__name__)

class Article:
    def __init__(self, slug):
        self.metadata = {'slug': slug}

ARTICLES = [Article('a'), Article('b')]

@app.route('/articles/<slug>/')
def article(slug):
    for article in ARTICLES:
        if article.metadata['slug'] == slug:
            return slug
    return page_not_found(404)

freezer = Freezer(app)

@freezer.register_generator
def article_generator():
    for article in ARTICLES:
        yield 'article', {'slug': article.metadata['slug']}

freezer.freeze()

```

**Comment by Zenahr** [comment]
@encukou yes, ARTICLES do exist.
Running your script over my ARTICLES works perfectly fine too.

Apparently there's just something wrong with the `deploy.py` script I wrote according to the docs. Running the same code via this script yields the same error as before:

```py
# deploy.py

from flask_frozen import Freezer
from app import app

app.config['FREEZER_RELATIVE_URLS'] = True
app.config['FREEZER_DESTINATION'] = 'public'

freezer = Freezer(app)

if __name__ == '__main__':
    freezer.freeze()
```

with `app.py` being:

```py
# app.py

from flask import Flask
from flask_frozen import Freezer

app = Flask(__name__)
freezer = Freezer(app)

@app.route('/articles/<slug>/')
def article(slug):
    for article in ARTICLES:
        if article.metadata['slug'] == slug:
            return slug
    return page_not_found(404)


@freezer.register_generator
def article_generator():
    for article in ARTICLES:
        yield 'article', {'slug': article.metadata['slug']}
```

error message:

```
MissingURLGeneratorWarning: Nothing frozen for endpoints article. Did you forget a URL generator?
  return set(page.url for page in self.freeze_yield())
```

Could you explain why this is happening? Am I invoking freeze() wrongly?

Anyways, discarding the `deploy.py` script and just running freeze() from within `app.py` solves the problem.

**Comment by encukou** [comment]
Sometimes the way things are loaded depends on the current directory: I'd check that `from app import app` imports the right module, and that `ARTICLES` is not empty when you import `app` this way.
But that's just a guess; without seeing your app it's hard to guess better.

**Comment by Zenahr** [comment]
yeah the imports are correct. I've double-checked that.
Anyway, I got the deploy-script working successfully by just invoking the freezer object from `app.py` directly instead of creating it seperately like so (in case someone else stumbles across this issue):

```
# app.py

from flask_frozen import Freezer

app = Flask(__name__)
freezer = Freezer(app, True)
...
...
...
```

```py
# deploy.py

from app import freezer

if __name__ == '__main__':
    freezer.freeze()
```

Thanks for your great help @encukou ! Much appreciated.
