### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by encukou** [Frozen-Flask/Frozen-Flask#117]
https://pythonhosted.org/Frozen-Flask/ does not show the latest content from `docs/`.
This might be solved by moving to Read The Docs (#80).

**Comment by honzajavorek** [comment]
I never had any docs on pythonhosted.org and I'm unsure about how to publish them there. If it's a matter of running one command, I'm happy to update them. Otherwise #80 to the rescue.

**Comment by sean-lockwood** [comment]
Pythonhosted used to be populated by PyPI, but it's now deprecated. Updates are no longer allowed other than removing docs.

**Comment by encukou** [comment]
@sean-lockwood, would you happen to know who can remove the docs on Pythonhosted?
(It would be nice to put in a redirect if that's possible, but if not, I think that removing it altogether is better than having outdated docs.)

**Comment by sean-lockwood** [comment]
Any pip maintainers: honzajavorek, max-k, SimonSapin, TimSwast

I would get the RTD build working first though.

**Comment by liZe** [comment]
Done!
