### ISSUE TITLE
Question about URL generators

### ISSUE THREAD

**Issue by ghost** [Frozen-Flask/Frozen-Flask#123]
So, I am making a blog and I am trying to freeze it with Frozen-Flask. I have the following URL generator in my code:
```
@app.route('/blog/<path:path>.html')
def page(path):
    page = pages.get_or_404(path)
    return render_template('page.html', page=page)
```
How can I make Frozen-Flask register the URL generator?

**Comment by TomHall2020** [comment]
If you have used that url endpoint in other pages that are frozen, it should automatically follow those urls and freeze them.

Else if you want to force it, you can use `@freezer.register_generator` in a few different ways (but bear in mind users would then have to know to type the url directly into the browser to access them as you're not linking to these pages from anywhere). Here's one implementation
```
@freezer.register_generator
def blog_pages_generator():
   for page_object in pages:
        yield url_for(page, page=page_object)
```

See [url-generators](https://pythonhosted.org/Frozen-Flask/#url-generators) in the documentation
