### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by githubVladimirT** [Frozen-Flask/Frozen-Flask#125]
Please, replace "`from collections import Mapping`" to "`from collections.abc import Mapping`" in `__init__.py`

Thank you!

(Flask frozen version 0.15)
(Python 3.10)

**Comment by mdaeron** [comment]
Does this mean Frozen-Flask will not/never be compatible with Python 3.10?

**Comment by githubVladimirT** [comment]
If I installing Flask-Frozen from github, I don't have this error.

I think that in PyPi placed old version of Flask-Frozen.
