### ISSUE TITLE
Ignore certain endpoints

### ISSUE THREAD

**Issue by mblayman** [Frozen-Flask/Frozen-Flask#29]
Ok, I think I have a real "issue" this time. :)

I am running my app through Frozen Flask and the app has basic CRUD operations. The problem that I'm encountering is that the freeze process is following the delete endpoint. This has the unfortunate side-effect of actually deleting all the page content in my app. Thus, the next time I run the freeze method, there is a lot less frozen stuff.

I didn't see any method in the documentation for getting freeze to ignore certain endpoints. Is this possible or desired?

**Comment by iurisilvio** [comment]
Same use case here. Frozen-Flask breaks with Flask-Admin and these will never be static.

**Comment by SimonSapin** [comment]
> Same use case here.

Same response here.

A blacklist is not implemented, but you can do what’s effectively a whitelist. Have you read the rest of this thread?

**Comment by iurisilvio** [comment]
To make the whitelist I have to disable some magic route discovering. I want `with_no_argument_rules` for most cases, but I want to ignore some endpoints.

I overriden `Freezer._build_one` to filter whatever I want without disabling route discovering.

**Comment by SimonSapin** [comment]
[`no_argument_rules_urls`](https://github.com/SimonSapin/Frozen-Flask/blob/e795c1869a70f3d3735b2f2b1d27dbddbac48368/flask_frozen/__init__.py#L396) is 3 lines of code. You can copy it and modify it.

**Comment by iurisilvio** [comment]
Ok. It is better than my solution. Thanks!

**Comment by mikenerone** [comment]
My use case is similar in that I want to exclude a few routes, except I also want (most of) the routes generated by `url_for_logger`. My app is mostly and API, but for easy human consumption with a browser most of the pages are viewable as HTML, differentiated based on the request Accept header (hey, standards!). A few of the routes are simply not useful for human consumption, though, so they have no Jinja2 templates and thus generate an error if requested as HTML. This caused `Freezer` to barf.

For now, I'm just wrapping the url_for_logger generator with my own to add the filtering I need (I also have to hack in support for request headers, which I think is an even more basic thing that Frozen-Flask should be able to do), but I will at least suggest that the simplest possible general implementation would be to allow a blacklist callable to be passed into `Freezer()` or `freeze()`. That callable would be passed each url or (endpoint, values) tuple yielded by the generators and be given a chance to veto (maybe return T/F, maybe raise an exception to filter, whatever you like). This would be very little code in Frozen-Flask yet be flexible enough for anything I can think of at the moment.

**Comment by mikenerone** [comment]
Just noticed #44. As an endpoint-based filter, that looks spot-on.
