### ISSUE TITLE
Add configuration to avoid generating pages for redirects

### ISSUE THREAD

**Issue by Undeterminant** [Frozen-Flask/Frozen-Flask#42]
Right now, it basically copies the files, which is a bit excessive.

**Comment by tswast** [comment]
As I commented in #59, if we don't want to add an HTML meta refresh to simulate a redirect, then it might be nice to add a configuration that throws an error on redirects / doesn't follow redirects. Would you be open to a PR that adds a config to not follow redirects (and thus throw an error / warning for unexpected status codes)?

With such a config I can be sure to remove all `flask.redirect` calls from my site and manually create an HTML meta refresh template instead, preventing duplicate content from appearing on the site.
