### ISSUE TITLE
Ignore endpoints in no_argument_rules()?

### ISSUE THREAD

**Issue by daboross** [Frozen-Flask/Frozen-Flask#45]
I'm currently using Frozen-Flask to generate static content for my website, to be served by Nginx. However, I'm also using flask running normally provide dynamic content for the website. With nginx's 'try_urls' ability, if Frozen-Flask generates a static page it's served by nginx, otherwise the request is forwarded to the Flask app running normally.

The one problem with this setup is that Frozen-Flask generates static pages for the paths which should be dynamic. Because they accept parameters in the form of `?param=value`, Frozen-Flask sees them as 'no_argument' rules, and thus static files are generated where the app should serve dynamic ones.

This is my current workaround:

```
app.config['FREEZER_IGNORE_ENDPOINTS'] = ['endpoint1', 'endpoint2']


# This is a copy of Freezer.no_argument_rules() modified to ignore certain paths
def no_argument_rules_urls_with_ignore():
    """URL generator for URL rules that take no arguments."""
    ignored = app.config.get('FREEZER_IGNORE_ENDPOINTS', [])
    for rule in app.url_map.iter_rules():
        if rule.endpoint not in ignored and not rule.arguments and 'GET' in rule.methods:
            yield rule.endpoint, {}


freezer = Freezer(app=app, with_no_argument_rules=False)
freezer.register_generator(no_argument_rules_urls_with_ignore)
```

Could something like this be included in Frozen-Flask by default?

This is similar to https://github.com/SimonSapin/Frozen-Flask/pull/44, but I don't think Frozen-Flask needs to process all generated urls, just ones in no_argument_rules. All other generated urls can be controlled other ways, either by the user editing his/her generators, or adding `with_static_files=False`.

**Comment by rebootl** [comment]
Thanks very much for the code snippet! Very useful, pity it's not included. A use case with e.g. a separate login area that you want to exclude from freezing is probably not that rare. And not everyone can easily write this code.
Anyways thanks for frozen-flask too.
