### ISSUE TITLE
CLI freezer

### ISSUE THREAD

**Issue by calvin** [Frozen-Flask/Frozen-Flask#46]
Hi Simon,

First of all, thanks for the package. It works beautifully.

Having said that, I think it would be nicer if it comes with a command line interface that generates static files without worrying about custom URL generators. So I'm proposing a command with the following interface:

    $ flask-freezer [OPTIONS] APP_MODULE space-separated-urls < additional-new-line-separated-urls

where: 
- `[OPTIONS]` are the same as current `frozen_flask` options. (i.e. `destination`, `destination-ignore`, etc)
- `APP_MODULE` is of the pattern `$(MODULE_NAME):$(FLASK_VARIABLE_NAME)`.
- `space-separated-urls` is a list of urls to be used in the generator

Additionally, the command can accept list of urls via `stdin`. 

Internally, it would a create  `Freezer` instance and with an URL generator that iterates over the URLs.

Thoughts?

**Comment by SimonSapin** [comment]
I’m not convinced this is that useful (you’re already writing Python code for your app anyway), and I’m slightly worried that this command-line interface will grow (through requests from various people) until it exposes (and duplicates) the entire Python API.
