### ISSUE TITLE
Frozen-Flask and Flask-Bable(ex)

### ISSUE THREAD

**Issue by matrixise** [Frozen-Flask/Frozen-Flask#53]
Hi all,

If we use Babel, we have to define a localeselector function where we will use the right locale in function of the parameters of the browser. But in the case of Frozen-Flask, how can we simulate the selection of a language ? For example, french or english ?

The reason, I would like to freeze an i18n website.

Is it possible? I don't have a code to explain, but it's just a question.

Thank you,

**Comment by SimonSapin** [comment]
Let’s forget Babel and Frozen-Flask for a minute.

If you only have a bunch of static files served by a "dumb" (default configuration) HTTP server, the HTTP `Accept-Language` request header can does not influence at all the response for a given URL.

So you want a non-default configuration, and it all depends on which HTTP server you’re using. Apache for example calls this "content negotiation", and has infinite variations of ways to configure it.

One you’ve figured out what file structure you need (maybe it involves having `index.html.en` and `index.html.fr` files next to each other), then go back to Frozen-Flask and consider how to generate these files. It helps to think as Frozen-Flask not as responding directly to requests from browsers (it doesn’t) but as a fancy `Makefile` to generate a bunch of files. For example, you could even [use `@app.route('/.htaccess')`](https://github.com/SimonSapin/exyr.org/blob/574a3c4b08cda455bfda4011c60a0ae61d8070b0/exyr/__init__.py#L118-L123).
