### ISSUE TITLE
0.12 tag missing

### ISSUE THREAD

**Issue by vext01** [Frozen-Flask/Frozen-Flask#57]

**Comment by vext01** [comment]
0.12 is released on pypi, but there is no tag in git.

Thanks

**Comment by tswast** [comment]
Just added the tag https://github.com/Frozen-Flask/Frozen-Flask/releases/tag/v0.12

The only difference between the version on PyPi and the latest commit on master was the version number, so I updated that in https://github.com/Frozen-Flask/Frozen-Flask/pull/62
