### ISSUE TITLE
Protected pages?

### ISSUE THREAD

**Issue by jredd** [Frozen-Flask/Frozen-Flask#58]
I was looking into this module for archiving pages for audit purposes but the site i'm developing has protected pages. Is there any configuration settings that will allow frozen to still capture protected pages?

**Comment by SimonSapin** [comment]
Protected how? HTTP Basic authentication, login `<form>` + cookie, something else?

**Comment by jredd** [comment]
I'm using flask-login for the logging in and logging out of users so typical form and cookie

**Comment by SimonSapin** [comment]
My recommendation would be to have different code paths for serving the site directly over HTTP and for "freezing" it. The latter would disable Flask-Login entirely.

**Comment by kmcelwee** [comment]
@jredd (6 years later, same issue 😄) FWIW: I was able to get this working by clearing out the flask login decorator on all my views:

```python
# views.py
class DataView(MethodView):
    decorators = [flask_login.login_required]

    def get(self, messages=None):
        if not messages:
            messages = []

        # NOTE: Just pass self?
        return render_template(f"data-view.html",)
```

And then in your static site generator script:
```python
# static-site-generator.py
from app import create_app
from app.views import DataView

DataView.decorators = []
app = create_app("app")
```
Assuming your app is structured similarly to mine, iterating through your views and removing the `flask_login.login_required` decorator then opens up the freezer client to route to your views without having to login.
