### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by SimonSapin** [Frozen-Flask/Frozen-Flask#61]
Hi all,

Having moved on to other things, I’m not interested in spending time on Frozen-Flask anymore. It has been effectively abandoned for some time. Still, there are a few open issues and pull requests and people occasionally file/submit new ones. The project needs a maintainer to live on, but it won’t be me.

I’ve you’d like to do this, comment here and I’ll give you access on github and PyPI. (Please include your PyPI username in the comment.)

CC people who have contributed pull requests: @tswast, @smbsimon, @MykolaBilyi, @mblayman, @aventurella, @singingwolfboy, @sodastsai, @mivade, @max-k, @HeyImAlex, @homeworkprod, @croach, @grayj, @vaus, @equalsraf, @benvinegar, @jokull, @amit-bansil, @rduplain.

**Comment by tswast** [comment]
I'm using Frozen-Flask actively at the moment, so would be okay with being a maintainer.

**Comment by SimonSapin** [comment]
Thanks a lot! I’ve invited you to the github org. Do you have a PyPI account?

**Comment by tswast** [comment]
Yes. Username: TimSwast

*  •  **Tim Swast*
*  •  *Developer Programs Engineer
*  •  *Google Cloud DevRel

**Comment by SimonSapin** [comment]
Alright, added you to https://pypi.python.org/pypi/Frozen-Flask

**Comment by tswast** [comment]
Closing this issue, but if anyone else wants to help with the maintenance, I'm open to volunteers.

**Comment by max-k** [comment]
If you need some help. I'm on it.

**Comment by tswast** [comment]
Thanks, Thomas! I would like some help and extra redundancy. I'll add you to the GitHub org and PyPi.

I'd really love if we could follow a process like [C4](http://rfc.zeromq.org/spec:22) (link seems broken at the moment), where I can write a PR and then another maintainer merges it. It feels wrong to me to merge my own PRs as I have done a few times already for this project to prepare the latest release.

**Comment by tswast** [comment]
@max-k What's your PyPI account name (if you have one)?

**Comment by max-k** [comment]
Hi, i completely agree with you about the merge process.

My PyPi account is max-k.


--
Thomas Sarboni

2016-10-11 19:48 GMT+02:00 Tim Swast <notifications@github.com>:
