### ISSUE TITLE
Feature Request : Skip existing files

### ISSUE THREAD

**Issue by Goutte** [Frozen-Flask/Frozen-Flask#69]
Hello !

I'm generating a huge website (the generation can take several days, and yes I optimized it as best as I can) ; some pages are quite long to generate (about half a minute).

I plan on adding more pages in the future, and I'd rather not re-generate everything every time.
I know I can mess with my URL generators to hack that feature, but it's dirty and not good design. Besides, I have to guess what the output file's name will be, and frozen-flask already knows this internally.

So I'm suggesting a `FREEZER_SKIP_EXISTING` configuration option, defaulted to `False`. ~~Is this doable ?~~ Would you agree ?

**Comment by Goutte** [comment]
I went as far as to make

**Comment by Goutte** [comment]
I went ahead and wrote a test for this :

``` python
def test_skip_existing_files(self):
    with self.make_app() as (temp, app, freezer):
        app.config['FREEZER_SKIP_EXISTING'] = True
        with open(os.path.join(temp, 'skipped.html'), 'w') as f:
            f.write("6*9")
        @app.route(u'/skipped.html')
        def test_sef():
            return '42'
        freezer.freeze()
        with open(os.path.join(temp, 'skipped.html')) as f:
            self.assertEqual(f.read(), '6*9')
```

I really like the source of frozen-flask, now that I've had a look at it. :confetti_ball:

---

Now, time to get `$ python -m flask_frozen.tests` crackin' !

**Comment by Goutte** [comment]
... and it's done ! **All tests pass.** ™

Damn. That is a nice code base you have there ! _(would be a shame if something happened to it, eh ?)_

I did not update the documentation yet, but I did correct a bunch of minor typos and PEP-8 non-compliances as I was reading along.

---

I'll look into the documentation. My changes should not impact performance much (one boolean check and loading of one configuration value for each generated url).

**Comment by Goutte** [comment]
Something like this, perhaps ?

``` rst
``FREEZER_SKIP_EXISTING``
    If set to ``True`` (defaults ``False``), Frozen-Flask will skip the
    generation of files that already exist in the build directory,
    even if the contents would have been different. Useful if your generation
    takes up a very long time and you only want to generate new files.

    .. versionadded:: 0.14
```

**Comment by tswast** [comment]
This seems like a reasonable feature. Thanks for your contribution.
