### ISSUE TITLE
Should I expect Frozen-Flask to be slow?

### ISSUE THREAD

**Issue by hieu-n** [Frozen-Flask/Frozen-Flask#76]
My flask site is a product catalog which has about 2000 products. I attempted to use Frozen-Flask to freeze my site. However, `freezer.freeze() ` seems to take forever to complete. Is it expected? Or there might be something wrong with my site.

**Comment by tswast** [comment]
I haven't run a performance benchmark. Could you run a profiler to see where the time is being spent?
