### ISSUE TITLE
Best way to handle sessions?

### ISSUE THREAD

**Issue by owenbrown** [Frozen-Flask/Frozen-Flask#82]
Our company purchases advertising to drive users to our site.
We love the durability and scalability of Frozen Flask.
We need to be able to to pass parameters in when a user lands on the site, cookie the user, and then pass the session_id associated with the user when the user ultimately clicks on an affiliate referral link. 
What is the best way to do this with Frozen Flask?

**Comment by tswast** [comment]
Frozen Flask is for generating a static HTML site. User-specific logic should be implemented via JavaScript.
