### ISSUE TITLE
[Feature Request] Compile to single page js app.

### ISSUE THREAD

**Issue by kgpayne** [Frozen-Flask/Frozen-Flask#84]
Hi! It would be amazing if frozen-flask could compile the generated static files into a single html file (single page app), with routing controlled by one of the many js frameworks (Angular, React, Ember etc.).

**Comment by tswast** [comment]
Thanks for the feature request. What would it look like for Frozen-Flask to compile such pages? Right now it is very closely tied to using Flask's routing mechanism.

**Comment by honzajavorek** [comment]
I think this is a very cool idea, but I'm unsure there are resources among the maintainers to pursue such direction in development of the project. If there's anyone willing to work on this, let us know! I think, from the user's point of view, it could be almost as simple as a switch in the settings, but the implementation side is where the challenges await.

**Comment by dAnjou** [comment]
That sounds kinda backwards to me. Why wouldn't you use one of the mentioned frameworks directly? I think Frozen-Flask should keep its focus on freezing Flask apps and not turn into a code generator for JS frameworks.

**Comment by liZe** [comment]
> That sounds kinda backwards to me. Why wouldn't you use one of the mentioned frameworks directly? I think Frozen-Flask should keep its focus on freezing Flask apps and not turn into a code generator for JS frameworks.

Yes, I think that it’s a cool idea, but not really related to Frozen-Flask. It should be a whole different extension!
