### ISSUE TITLE
Relative URLs without /index.html ?

### ISSUE THREAD

**Issue by mvolfik** [Frozen-Flask/Frozen-Flask#90]
Hello,  
is it possible to add option like `FREEZER_RELATIVE_URLS_WITHOUT_INDEX`, which would disable adding `index.html` to paths like `../foobar/`? Because I develop application which is then frozen and served as normal website. I need relative urls, because it's not placed in web root, but I don't like that `index.html`.
I tried removing [lines 533 and 534](https://github.com/Frozen-Flask/Frozen-Flask/blob/master/flask_frozen/__init__.py#L533), but it created urls like `/foobar`. Can you please help?
Thanks, m.volfik

**Comment by tswast** [comment]
I don't understand. Where would the HTML content be written if not to `index.html`? If you are referring to relative links, any links generated are due to Flask and not controlled by Frozen-Flask.

**Comment by honzajavorek** [comment]
@mvolfik Were you able to resolve your issues after all? I'm trying to figure out if this is still relevant.

**Comment by mvolfik** [comment]
I don't really need this anymore, though I still think this might be useful. I'll try to explain it again:

If you want to host the Flask-Frozen files in non-root folder of a server, you have to use relative urls. However, these urls always include the full file path. What I wanted is that instead of `../folder/index.html` it would generate `../folder/`, and the server automatically serves the `index.html` file from that folder. This, of course, doesn't apply to other addresses than `*/index.html`

**Comment by liZe** [comment]
#127 is ready to be merged for me, don’t hesitate to test and give some feedback if needed.
