### ISSUE TITLE
Compatibility with Python 3.9

### ISSUE THREAD

**Issue by honzajavorek** [Frozen-Flask/Frozen-Flask#95]
I'm getting following warnings:

```
/Users/honza/.local/share/virtualenvs/python.cz-s2NxYiyq/lib/python3.7/site-packages/flask_frozen/__init__.py:29
  /Users/honza/.local/share/virtualenvs/python.cz-s2NxYiyq/lib/python3.7/site-packages/flask_frozen/__init__.py:29:
  DeprecationWarning: Using or importing the ABCs from 'collections' instead
  of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Mapping, namedtuple

tests/views_test.py::test_get_involved_cs_renders_ordinary_issue
  /Users/honza/.local/share/virtualenvs/python.cz-s2NxYiyq/lib/python3.7/site-packages/ics/icalendar.py:59:
  DeprecationWarning: Using or importing the ABCs from 'collections' instead
  of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    elif isinstance(imports, collections.Iterable):
```

**Comment by tswast** [comment]
Thanks for reporting. PRs welcome!

**Comment by hroncok** [comment]
Is preserving Python 2 compatibility required?

**Comment by tswast** [comment]
I'd lean towards keeping in line with the latest version of Flask, but they do still support Python 2.7. https://github.com/pallets/flask/blob/64ba43411fbfb2e435455b0df2453d7809b7c5a8/setup.py

I think it's probably worth dropping 2.7 so long as Python 3.5 is still supported.

**Comment by honzajavorek** [comment]
FYI, I'm getting [failures with Travis CI](https://travis-ci.org/github/Frozen-Flask/Frozen-Flask/builds/661954836) trying to install Py 2.x versions under https://github.com/Frozen-Flask/Frozen-Flask/pull/97. But it also fails to install the PyPy versions, so I'm unsure what's the issue.

**Comment by honzajavorek** [comment]
Added a tested solution here: https://github.com/Frozen-Flask/Frozen-Flask/pull/98

**Comment by jayaddison** [comment]
@tswast @honzajavorek Do you know if there are any plans to release a `py3.9`-compatible release of `Frozen-Flask` to PyPi?

**Comment by honzajavorek** [comment]
I think it's mainly a matter of whether there's a contribution adding the support.

I'm unsure whether it's a big task or not, given we still support 2.7. If supporting 3.9 is easier (and cleaner) without 2.7, there's probably no big harm in watching when Flask drops 2.7 and only then add support for 3.9. I don't have any strong opinions about this though.

**Comment by jayaddison** [comment]
Ok, that makes sense.  The good news: running the Flask-Frozen test suite under Python 3.9, it seems to pass as-is.  I'll open a pull request to enable CI in a moment.

**Comment by honzajavorek** [comment]
OK so previously I've replied from my phone and I missed the fact this is closed already. I recalled I wanted to tackle this problem in https://github.com/Frozen-Flask/Frozen-Flask/pull/98, which even mentions 3.9 and I think it tests the issues and fixes them, but for some reason, I forgot to add it to the testing matrix 😄 So that probably explains why it passes as-is.

**Comment by jayaddison** [comment]
No probs, thanks! :)
