### ISSUE TITLE
CI fails for Python 2.x versions and for PyPy

### ISSUE THREAD

**Issue by honzajavorek** [Frozen-Flask/Frozen-Flask#99]
Perhaps they removed the 2.x versions already? I've been searching the internet for a solution, but to no avail. It seems Flask itself [is using Azure pipelines](https://github.com/pallets/flask/blob/master/.azure-pipelines.yml), which still might have these available.

@tswast if you think it is a good idea, I might try to migrate the project to [GitHub Actions](https://github.com/features/actions) or sth like that. Let me know! I think it's important to have the CI green as otherwise it inhibits contributions.

**Comment by tswast** [comment]
Any work on CI is much appreciated.
